research_task:
  description: >
    Conduct a thorough and up-to-date research about {topic}.
    Gather factual, credible, and current information from multiple reliable sources.
    Identify any numerical data, performance metrics, feature comparisons, or trends
    that could be visualized in tables, charts, or plots.
    Make sure you consider the current year is {current_year}.
  expected_output: >
    A list with at least 10 bullet points of the most relevant, accurate,
    and interesting information about {topic}, including any measurable or
    comparable data points when possible.
  agent: researcher

analysis_task:
  description: >
    Using the research context provided, perform detailed data analysis.
    Extract and structure any numerical or categorical data into well-formatted tables.
    Generate at least one chart, graph, or plot that illustrates a meaningful comparison
    or trend related to {topic}. Use Markdown for tables and include image links for plots.
  expected_output: >
    A Markdown section containing:
    1. One or more tables comparing key aspects of {topic}
    2. At least one chart/graph/plot (embedded as an image)
    3. Short captions or explanations for each visual
  agent: reporting_analyst

composition_task:
  description: >
    Combine the narrative from the research, the tables, and the visuals from the analysis
    into a cohesive, engaging, and publication-ready article about {topic}.
    Ensure that the visuals are placed at relevant points in the text and the flow
    is logical. The tone should be clear, informative, and suitable for a professional audience.
  expected_output: >
    A complete Markdown-formatted article that includes:
    - An introduction setting the context
    - Detailed sections based on research findings
    - Integrated tables and visuals
    - A concise conclusion summarizing the insights
  agent: article_composer
